class CConfigurations {
  static const List<Map<String, String>> filterOptions = [
    { 'key': 'amplitude', 'label': 'Amplitude' },
    { 'key': 'average', 'label': 'Average' },
    { 'key': 'board', 'label': 'Board' },
    { 'key': 'contrast', 'label': 'Contrast' },
    { 'key': 'cow', 'label': 'Cow' },
    { 'key': 'current_low', 'label': 'Current Low' },
    { 'key': 'current_high', 'label': 'Current High' },
    { 'key': 'dragon_10', 'label': 'Dragon 10' },
    { 'key': 'dragon_30', 'label': 'Dragon 30' },
    { 'key': 'dragon_60', 'label': 'Dragon 60' },
    { 'key': 'dragon_365', 'label': 'Dragon 365' },
    { 'key': 'drop', 'label': 'Drop Back' },
    { 'key': 'high_open', 'label': 'High Open' },
    { 'key': 'low', 'label': 'Low' },
    { 'key': 'low_turnover', 'label': 'Low Turnover' },
    { 'key': 'money', 'label': 'Money' },
    { 'key': 'movement', 'label': 'Movement' },
    { 'key': 'premium', 'label': 'Premium' },
    { 'key': 'profit', 'label': 'Profit' },
    { 'key': 'profit_change', 'label': 'Profit Change' },
    { 'key': 'profit_lastday', 'label': 'Profit Lastday' },
    { 'key': 'profit_today', 'label': 'Profit Today' },
    { 'key': 'reverse', 'label': 'Reverse' },
    { 'key': 'strong', 'label': 'Strong' },
    { 'key': 'trend', 'label': 'Trend' },
    { 'key': 'turnover', 'label': 'Turnover' },
    { 'key': 'turnover_rate_avg_down', 'label': 'Turnover Rate Avg Down' },
    { 'key': 'turnover_rate_avg_5_down', 'label': 'Turnover Rate Avg 5 Down' },
    { 'key': 'turnover_rate_avg_10_down', 'label': 'Turnover Rate Avg 10 Down' },
    { 'key': 'turnover_rate_avg_30_down', 'label': 'Turnover Rate Avg 30 Down' },
    { 'key': 'turnover_rate_rise', 'label': 'Turnover Rate Rise' },
    { 'key': 'turnover_rate_avg_rise', 'label': 'Turnover Rate Avg Rise' },
    { 'key': 'turnover_rate_rise', 'label': 'Turnover Rate Rise' },
    { 'key': 'turnover_rise', 'label': 'Turnover Rise' },
    { 'key': 'turnover_rise_rate', 'label': 'Turnover Rise Rate' },
    { 'key': 'value', 'label': 'Value' },
    { 'key': 'volumn', 'label': 'Volumn' },
    { 'key': 'volumn_rate', 'label': 'Volumn Rate' },
  ];

  static const List<Map<String, String>> marketOptions = [
    { 'key': 'all', 'label': 'All' },
    { 'key': 'main', 'label': 'Main' },
    { 'key': 'second', 'label': 'Second' },
    { 'key': 'star', 'label': 'STAR' },
    { 'key': 'peking', 'label': 'Peking' },
    { 'key': 'sh', 'label': 'SH' },
    { 'key': 'sz', 'label': 'SZ' },
  ];
}